// GENERATED by scripts/build-registry.mjs. Do not edit.
export type ZCode = {
  /** Shiki output, already highlighted at build time. */
  html: string
  /** Byte-identical to the file on disk and to files[].content in /r/. */
  raw: string
  lines: number
  sha: string
  /** Where the CLI writes this file inside a consumer project. */
  target: string
}

/** Keyed `<item>/<file>`, e.g. `like-button/like-button.tsx`. */
export declare const code: Record<string, ZCode | undefined>
