// GENERATED by scripts/build-registry.mjs. Do not edit.
export const items = [
  {
    "name": "disclosure",
    "type": "registry:component",
    "title": "Disclosure",
    "description": "A panel whose height is an interruptible spring. Press again mid-open and it reverses from wherever it got to, carrying the speed it was already moving at.",
    "category": "state-morphing",
    "gesture": "press",
    "states": [
      "closed",
      "opening",
      "open",
      "closing"
    ],
    "spring": null,
    "motion": {
      "states": [
        "closed",
        "opening",
        "open",
        "closing"
      ],
      "springs": [
        {
          "name": "SPRING",
          "stiffness": 520,
          "damping": 46,
          "mass": 1,
          "restDelta": 2,
          "restSpeed": 20,
          "preset": null
        }
      ],
      "durations": [],
      "reducedMotion": "branch"
    },
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "disclosure",
        "files": [
          {
            "key": "disclosure/disclosure.tsx",
            "target": "components/z-ui/disclosure.tsx",
            "sha": "d397dd56c8f4"
          }
        ]
      }
    ]
  },
  {
    "name": "hold-drain",
    "type": "registry:component",
    "title": "Hold Drain",
    "description": "A hold-to-confirm whose abort costs what the hold earned. Let go at seventy per cent and the fill is paid back at the rate it climbed, taking exactly as long to undo as it took to earn.",
    "category": "tactile-feedback",
    "gesture": "hold",
    "states": [
      "idle",
      "filling",
      "armed",
      "committed",
      "draining"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "filling",
        "armed",
        "committed",
        "draining"
      ],
      "springs": [],
      "durations": [
        {
          "name": "duration",
          "ms": 1200
        }
      ],
      "reducedMotion": "branch"
    },
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "hold-drain",
        "files": [
          {
            "key": "hold-drain/hold-drain.tsx",
            "target": "components/z-ui/hold-drain.tsx",
            "sha": "1e5783274a16"
          }
        ]
      }
    ]
  },
  {
    "name": "scramble-reveal",
    "type": "registry:component",
    "title": "Scramble Reveal",
    "description": "Text that decodes out of random glyphs on hover, on mount, or when it first enters view.",
    "category": "state-morphing",
    "gesture": "hover",
    "states": [
      "idle",
      "scrambling",
      "settled"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "scrambling",
        "settled"
      ],
      "springs": [],
      "durations": [
        {
          "name": "duration",
          "ms": 620
        }
      ],
      "reducedMotion": "branch"
    },
    "dependencies": [],
    "installs": [
      {
        "name": "scramble-reveal",
        "files": [
          {
            "key": "scramble-reveal/scramble-reveal.tsx",
            "target": "components/z-ui/scramble-reveal.tsx",
            "sha": "e9736478c4f2"
          }
        ]
      }
    ]
  }
]
export const byName = Object.fromEntries(items.map((i) => [i.name, i]))
export const components = items.filter((i) => i.type === 'registry:component')
export const cliVersion = "0.1.1"
