// GENERATED by scripts/build-registry.mjs. Do not edit.
export type ZFile = { key: string; target: string; sha: string }
export type ZInstall = { name: string; files: ZFile[] }
export type ZItemType = 'registry:component' | 'registry:hook' | 'registry:lib'
/** The input that drives the component's signature motion. `none` is for a
 *  component with no driving gesture: its state is set programmatically. */
export type ZGesture = 'press' | 'drag' | 'hold' | 'hover' | 'type' | 'none'

export type ZPreset = 'snap' | 'bounce' | 'settle' | 'fling'

export type ZSpring = {
  name: string
  stiffness: number
  damping: number
  mass: number
  restDelta: number | null
  restSpeed: number | null
  /** The published preset these numbers match exactly, or null when bespoke. */
  preset: ZPreset | null
}
export type ZDuration = { name: string; ms: number }

/** Scanned out of the component source by scripts/motion-scan.mjs at build
 *  time. Never authored — lint-registry rejects a hand-written copy. */
export type ZMotion = {
  states: string[] | null
  springs: ZSpring[]
  durations: ZDuration[]
  reducedMotion: 'branch' | null
}

export type ZItem = {
  name: string
  type: ZItemType
  title: string
  description: string
  category: string | null
  gesture: ZGesture | null
  states: string[] | null
  spring: ZPreset | null
  motion: ZMotion | null
  dependencies: string[]
  installs: ZInstall[]
}

/**
 * Components always declare a category, a gesture and states, and always carry
 * scanned motion data. The spring field stays nullable: it names the preset the
 * component's own numbers match exactly, and a component that tuned its own
 * physics matches none.
 */
export type ZComponent = ZItem & {
  type: 'registry:component'
  category: string
  gesture: ZGesture
  states: string[]
  motion: ZMotion
}

export declare const items: ZItem[]
export declare const byName: Record<string, ZItem | undefined>
export declare const components: ZComponent[]
/** Read from packages/cli/package.json at build time, never typed into a page. */
export declare const cliVersion: string
