// GENERATED by scripts/build-registry.mjs. Do not edit.
export const items = [
  {
    "name": "like-button",
    "type": "registry:component",
    "title": "Like Button",
    "description": "A like toggle that overshoots on press and settles with a spring.",
    "category": "tactile-feedback",
    "states": [
      "idle",
      "hover",
      "pressing",
      "liked",
      "liked-hover",
      "liked-pressing"
    ],
    "spring": "bounce",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "use-controllable-state",
        "files": [
          {
            "key": "use-controllable-state/use-controllable-state.ts",
            "target": "hooks/use-controllable-state.ts",
            "sha": "1508d9ae5c2f"
          }
        ]
      },
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "like-button",
        "files": [
          {
            "key": "like-button/like-button.tsx",
            "target": "components/z-ui/like-button.tsx",
            "sha": "450dc25e83d5"
          }
        ]
      }
    ]
  },
  {
    "name": "scrub",
    "type": "registry:component",
    "title": "Scrub",
    "description": "A seek bar whose precision increases as the pointer pulls away from the track.",
    "category": "input-utility",
    "states": [
      "idle",
      "hover",
      "scrubbing",
      "scrubbing-fine",
      "settling"
    ],
    "spring": "settle",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "use-controllable-state",
        "files": [
          {
            "key": "use-controllable-state/use-controllable-state.ts",
            "target": "hooks/use-controllable-state.ts",
            "sha": "1508d9ae5c2f"
          }
        ]
      },
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "scrub",
        "files": [
          {
            "key": "scrub/scrub.tsx",
            "target": "components/z-ui/scrub.tsx",
            "sha": "48c7210e04e9"
          }
        ]
      }
    ]
  },
  {
    "name": "hold-to-confirm",
    "type": "registry:component",
    "title": "Hold To Confirm",
    "description": "A destructive action that costs a second of deliberate pressure, and unwinds if you let go.",
    "category": "input-utility",
    "states": [
      "idle",
      "hover",
      "holding",
      "releasing",
      "confirmed"
    ],
    "spring": "snap",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "hold-to-confirm",
        "files": [
          {
            "key": "hold-to-confirm/hold-to-confirm.tsx",
            "target": "components/z-ui/hold-to-confirm.tsx",
            "sha": "0e227d048773"
          }
        ]
      }
    ]
  },
  {
    "name": "undo-toast",
    "type": "registry:component",
    "title": "Undo Toast",
    "description": "A destructive action's grace period, with a visible clock that pauses when you reach for it.",
    "category": "input-utility",
    "states": [
      "counting",
      "held",
      "dragging",
      "leaving"
    ],
    "spring": "settle",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "undo-toast",
        "files": [
          {
            "key": "undo-toast/undo-toast.tsx",
            "target": "components/z-ui/undo-toast.tsx",
            "sha": "2221fc5f6894"
          }
        ]
      }
    ]
  },
  {
    "name": "disclosure",
    "type": "registry:component",
    "title": "Disclosure",
    "description": "An accordion panel whose height is a spring you can interrupt mid-flight, not a duration that has to finish first.",
    "category": "state-morphing",
    "states": [
      "closed",
      "hover",
      "opening",
      "open",
      "closing"
    ],
    "spring": "settle",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "use-controllable-state",
        "files": [
          {
            "key": "use-controllable-state/use-controllable-state.ts",
            "target": "hooks/use-controllable-state.ts",
            "sha": "1508d9ae5c2f"
          }
        ]
      },
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "disclosure",
        "files": [
          {
            "key": "disclosure/disclosure.tsx",
            "target": "components/z-ui/disclosure.tsx",
            "sha": "5e9669656c4a"
          }
        ]
      }
    ]
  },
  {
    "name": "sheet",
    "type": "registry:component",
    "title": "Sheet",
    "description": "A draggable panel that snaps to the detent your release velocity projects toward, not the one nearest where your hand happened to stop.",
    "category": "input-utility",
    "states": [
      "closed",
      "dragging",
      "settling",
      "open"
    ],
    "spring": "settle",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "sheet",
        "files": [
          {
            "key": "sheet/sheet.tsx",
            "target": "components/z-ui/sheet.tsx",
            "sha": "a34947f5a7a0"
          }
        ]
      }
    ]
  },
  {
    "name": "reorder",
    "type": "registry:component",
    "title": "Reorder",
    "description": "A drag-to-reorder list where the displaced rows don't move together — each settles with a spring softened by its distance from the row you dragged, so the shift travels down the list as a wave.",
    "category": "input-utility",
    "states": [
      "idle",
      "dragging",
      "settling"
    ],
    "spring": "snap",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "reorder",
        "files": [
          {
            "key": "reorder/reorder.tsx",
            "target": "components/z-ui/reorder.tsx",
            "sha": "7fafa5d79c90"
          }
        ]
      }
    ]
  },
  {
    "name": "slide-to-confirm",
    "type": "registry:component",
    "title": "Slide To Confirm",
    "description": "A drag-to-commit gesture that fails safe with a recoil carrying your release velocity, so how close the attempt got is something you feel, not just a snap back to zero.",
    "category": "input-utility",
    "states": [
      "idle",
      "hover",
      "dragging",
      "snapping-back",
      "confirmed"
    ],
    "spring": "bounce",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "slide-to-confirm",
        "files": [
          {
            "key": "slide-to-confirm/slide-to-confirm.tsx",
            "target": "components/z-ui/slide-to-confirm.tsx",
            "sha": "eafc56929c34"
          }
        ]
      }
    ]
  },
  {
    "name": "revert-field",
    "type": "registry:component",
    "title": "Revert Field",
    "description": "A text field where Escape rewinds an edit as a watched un-typing, deleting to the shared prefix and typing the prior value back in, instead of silently snapping the string back.",
    "category": "input-utility",
    "states": [
      "idle",
      "hover",
      "editing",
      "reverting"
    ],
    "spring": "snap",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "use-controllable-state",
        "files": [
          {
            "key": "use-controllable-state/use-controllable-state.ts",
            "target": "hooks/use-controllable-state.ts",
            "sha": "1508d9ae5c2f"
          }
        ]
      },
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "revert-field",
        "files": [
          {
            "key": "revert-field/revert-field.tsx",
            "target": "components/z-ui/revert-field.tsx",
            "sha": "a8a72ec61e62"
          }
        ]
      }
    ]
  },
  {
    "name": "scheduler",
    "type": "registry:component",
    "title": "Scheduler",
    "description": "A date-and-time booking picker where hovering a slot raises a dim, question-marked preview of the confirmation before you've committed to anything, and month navigation is an interruptible spring, not a crossfade.",
    "category": "input-utility",
    "states": [
      "browsing",
      "previewing",
      "committed"
    ],
    "spring": "settle",
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "use-controllable-state",
        "files": [
          {
            "key": "use-controllable-state/use-controllable-state.ts",
            "target": "hooks/use-controllable-state.ts",
            "sha": "1508d9ae5c2f"
          }
        ]
      },
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      },
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      },
      {
        "name": "scheduler",
        "files": [
          {
            "key": "scheduler/scheduler.tsx",
            "target": "components/z-ui/scheduler.tsx",
            "sha": "57de09e2651e"
          }
        ]
      }
    ]
  },
  {
    "name": "use-controllable-state",
    "type": "registry:hook",
    "title": "Use Controllable State",
    "description": "State that is uncontrolled by default and controlled when a value is passed.",
    "category": "primitive",
    "states": null,
    "spring": null,
    "dependencies": [],
    "installs": [
      {
        "name": "use-controllable-state",
        "files": [
          {
            "key": "use-controllable-state/use-controllable-state.ts",
            "target": "hooks/use-controllable-state.ts",
            "sha": "1508d9ae5c2f"
          }
        ]
      }
    ]
  },
  {
    "name": "z-cn",
    "type": "registry:lib",
    "title": "Z Class Names",
    "description": "Class name merge helper that resolves conflicting Tailwind utilities in favor of the consumer.",
    "category": "primitive",
    "states": null,
    "spring": null,
    "dependencies": [
      "clsx",
      "tailwind-merge"
    ],
    "installs": [
      {
        "name": "z-cn",
        "files": [
          {
            "key": "z-cn/z-cn.ts",
            "target": "lib/z-cn.ts",
            "sha": "01832b4bf9ea"
          }
        ]
      }
    ]
  },
  {
    "name": "z-spring",
    "type": "registry:lib",
    "title": "Z Spring",
    "description": "The Z-UI spring scale and the transition hook that honors prefers-reduced-motion.",
    "category": "primitive",
    "states": null,
    "spring": null,
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "z-spring",
        "files": [
          {
            "key": "z-spring/z-spring.ts",
            "target": "lib/z-spring.ts",
            "sha": "8036154529ed"
          }
        ]
      }
    ]
  }
]
export const byName = Object.fromEntries(items.map((i) => [i.name, i]))
export const components = items.filter((i) => i.type === 'registry:component')
