// GENERATED by scripts/build-registry.mjs. Do not edit.
export const items = [
  {
    "name": "disclosure",
    "type": "registry:component",
    "title": "Disclosure",
    "description": "A panel whose height is an interruptible spring. Press again mid-open and it reverses from wherever it got to, carrying the speed it was already moving at.",
    "category": "state-morphing",
    "gesture": "press",
    "states": [
      "closed",
      "opening",
      "open",
      "closing"
    ],
    "spring": null,
    "motion": {
      "states": [
        "closed",
        "opening",
        "open",
        "closing"
      ],
      "springs": [
        {
          "name": "SPRING",
          "stiffness": 520,
          "damping": 46,
          "mass": 1,
          "restDelta": 2,
          "restSpeed": 20,
          "preset": null
        }
      ],
      "durations": [],
      "reducedMotion": "branch"
    },
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "disclosure",
        "files": [
          {
            "key": "disclosure/disclosure.tsx",
            "target": "components/z-ui/disclosure.tsx",
            "sha": "559d5361dff1"
          }
        ]
      }
    ]
  },
  {
    "name": "hold-drain",
    "type": "registry:component",
    "title": "Hold Drain",
    "description": "A hold-to-confirm whose abort costs what the hold earned. Let go at seventy per cent and the fill is paid back at the rate it climbed, taking exactly as long to undo as it took to earn.",
    "category": "tactile-feedback",
    "gesture": "hold",
    "states": [
      "idle",
      "filling",
      "armed",
      "committed",
      "draining"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "filling",
        "armed",
        "committed",
        "draining"
      ],
      "springs": [],
      "durations": [
        {
          "name": "duration",
          "ms": 1200
        }
      ],
      "reducedMotion": "branch"
    },
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "hold-drain",
        "files": [
          {
            "key": "hold-drain/hold-drain.tsx",
            "target": "components/z-ui/hold-drain.tsx",
            "sha": "1e5783274a16"
          }
        ]
      }
    ]
  },
  {
    "name": "late-critique",
    "type": "registry:component",
    "title": "Late Critique",
    "description": "A field whose criticism is late and whose forgiveness is instant. No verdict lands mid-word — it waits for a pause — and once it is complaining, the first keystroke that fixes the value clears it on the same frame.",
    "category": "input-utility",
    "gesture": "type",
    "states": [
      "idle",
      "typing",
      "settling",
      "invalid",
      "recovering",
      "valid"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "typing",
        "settling",
        "invalid",
        "recovering",
        "valid"
      ],
      "springs": [],
      "durations": [
        {
          "name": "DEFAULT_QUIET_MS",
          "ms": 700
        },
        {
          "name": "LEAVE_MS",
          "ms": 120
        }
      ],
      "reducedMotion": "branch"
    },
    "dependencies": [],
    "installs": [
      {
        "name": "late-critique",
        "files": [
          {
            "key": "late-critique/late-critique.tsx",
            "target": "components/z-ui/late-critique.tsx",
            "sha": "7b371ddc7520"
          }
        ]
      }
    ]
  },
  {
    "name": "scramble-reveal",
    "type": "registry:component",
    "title": "Scramble Reveal",
    "description": "Text that decodes out of random glyphs on hover, on mount, or when it first enters view.",
    "category": "state-morphing",
    "gesture": "hover",
    "states": [
      "idle",
      "scrambling",
      "settled"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "scrambling",
        "settled"
      ],
      "springs": [],
      "durations": [
        {
          "name": "duration",
          "ms": 620
        }
      ],
      "reducedMotion": "branch"
    },
    "dependencies": [],
    "installs": [
      {
        "name": "scramble-reveal",
        "files": [
          {
            "key": "scramble-reveal/scramble-reveal.tsx",
            "target": "components/z-ui/scramble-reveal.tsx",
            "sha": "7a2c79b51357"
          }
        ]
      }
    ]
  },
  {
    "name": "heft",
    "type": "registry:component",
    "title": "Heft",
    "description": "A box of objects that behave like objects. Drag one and everything it touches is shoved aside; anything resting on top loses its floor and drops. Axis-aligned rigid bodies, sequential impulses with warm starting, gravity, contacts and friction — in one file, with its stylesheet beside it.",
    "category": "tactile-feedback",
    "gesture": "drag",
    "states": [
      "idle",
      "dragging",
      "settling"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "dragging",
        "settling"
      ],
      "springs": [],
      "durations": [],
      "reducedMotion": "branch"
    },
    "dependencies": [],
    "installs": [
      {
        "name": "heft",
        "files": [
          {
            "key": "heft/heft.tsx",
            "target": "components/z-ui/heft.tsx",
            "sha": "7b2ed2ce63d1"
          },
          {
            "key": "heft/heft.css",
            "target": "components/z-ui/heft.css",
            "sha": "e4e29fa99e9d"
          }
        ]
      }
    ]
  },
  {
    "name": "dial",
    "type": "registry:component",
    "title": "Dial",
    "description": "A knob with a flywheel in it. Flick it and it spins down through real friction, ticking over detents until the nearest one catches it with a spring. Grab it mid-spin and the spin is yours again.",
    "category": "tactile-feedback",
    "gesture": "drag",
    "states": [
      "idle",
      "turning",
      "coasting"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "turning",
        "coasting"
      ],
      "springs": [
        {
          "name": "SPRING",
          "stiffness": 1300,
          "damping": 46,
          "mass": 1,
          "restDelta": null,
          "restSpeed": null,
          "preset": null
        }
      ],
      "durations": [],
      "reducedMotion": "branch"
    },
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "dial",
        "files": [
          {
            "key": "dial/dial.tsx",
            "target": "components/z-ui/dial.tsx",
            "sha": "14759bd3ab84"
          }
        ]
      }
    ]
  },
  {
    "name": "chase",
    "type": "registry:component",
    "title": "Chase",
    "description": "A segmented control whose indicator gives chase: the edge facing the target leaves on a stiff spring, the edge behind follows on a soft one, and the stretch between them is the speed. Nothing scripts the squash.",
    "category": "state-morphing",
    "gesture": "press",
    "states": [
      "idle",
      "moving"
    ],
    "spring": null,
    "motion": {
      "states": [
        "idle",
        "moving"
      ],
      "springs": [
        {
          "name": "SPRING_LEAD",
          "stiffness": 950,
          "damping": 62,
          "mass": 1,
          "restDelta": 0.5,
          "restSpeed": 5,
          "preset": null
        },
        {
          "name": "SPRING_TRAIL",
          "stiffness": 380,
          "damping": 34,
          "mass": 1,
          "restDelta": 0.5,
          "restSpeed": 5,
          "preset": null
        }
      ],
      "durations": [],
      "reducedMotion": "branch"
    },
    "dependencies": [
      "motion"
    ],
    "installs": [
      {
        "name": "chase",
        "files": [
          {
            "key": "chase/chase.tsx",
            "target": "components/z-ui/chase.tsx",
            "sha": "210a4b1e426a"
          }
        ]
      }
    ]
  }
]
export const byName = Object.fromEntries(items.map((i) => [i.name, i]))
export const components = items.filter((i) => i.type === 'registry:component')
export const cliVersion = "0.1.1"
